DEFINE GRANT USAGE ON DATABASE DEMO{{env_suffix}} TO ROLE ACCOUNTADMIN;
DEFINE GRANT USAGE ON DATABASE DEMO{{env_suffix}} TO ROLE CORTEX_USER_ROLE;
DEFINE GRANT USAGE ON DATABASE DEMO{{env_suffix}} TO ROLE PUBLIC;
