DEFINE TABLE DEMO{{env_suffix}}.DT_DEMO.CUST_INFO (
    CUSTID NUMBER(10,0),
    CNAME VARCHAR(100),
    SPENDLIMIT NUMBER(10,2)
);

DEFINE TABLE DEMO{{env_suffix}}.DT_DEMO.PROD_STOCK_INV (
    PID NUMBER(10,0),
    PNAME VARCHAR(100),
    STOCK NUMBER(10,2),
    STOCKDATE DATE
);

DEFINE TABLE DEMO{{env_suffix}}.DT_DEMO.PROD_STOCK_INV1 (
    PID NUMBER(10,0),
    PNAME VARCHAR(100),
    STOCK NUMBER(10,2),
    STOCKDATE DATE
);

DEFINE TABLE DEMO{{env_suffix}}.DT_DEMO.SALESDATA (
    CUSTID NUMBER(10,0),
    PURCHASE VARIANT
);
