DEFINE DATABASE DEMO{{env_suffix}};

DEFINE SCHEMA DEMO{{env_suffix}}.PUBLIC;

DEFINE SCHEMA DEMO{{env_suffix}}.DT_DEMO;

DEFINE SCHEMA DEMO{{env_suffix}}.RESTRO;

DEFINE STAGE DEMO{{env_suffix}}.PUBLIC.YAML_INT_STG;
